export const FEATURES = [
  {
    key: 'powder-reuse-plan',
    name: 'Powder Reuse Plan',
    shortName: 'Powder Reuse',
    description: 'Track powder lot reuse cycles, virgin blend percentage, moisture, and tensile risk before release.',
    icon: '♻️',
    isAI: false,
    color: '#0d9488',
    apiPath: '/powder-reuse-plan',
    columns: [
      { key: 'lot_id', label: 'Lot' },
      { key: 'material', label: 'Material' },
      { key: 'reuse_cycle', label: 'Reuse Cycle' },
      { key: 'virgin_blend_pct', label: 'Virgin %' },
      { key: 'moisture_ppm', label: 'Moisture ppm' },
      { key: 'tensile_risk', label: 'Tensile Risk', type: 'risk' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { key: 'lot_id', label: 'Lot ID', type: 'text', required: true },
      { key: 'material', label: 'Material', type: 'text' },
      { key: 'reuse_cycle', label: 'Reuse Cycle', type: 'number' },
      { key: 'virgin_blend_pct', label: 'Virgin Blend %', type: 'number' },
      { key: 'moisture_ppm', label: 'Moisture ppm', type: 'number' },
      { key: 'tensile_risk', label: 'Tensile Risk', type: 'select', options: ['low', 'medium', 'high'] },
      { key: 'status', label: 'Status', type: 'text' },
    ],
  },
  {
    key: 'print-parameters',
    name: 'Print Parameter Tuning',
    shortName: 'Parameter Tuning',
    description: 'AI-powered optimization of print parameters by material type and geometry. Get optimal layer height, temperature, speed, and infill settings.',
    icon: '\u2699\uFE0F',
    isAI: true,
    color: '#8b5cf6',
    apiPath: '/print-parameters',
    aiEndpoint: '/print-parameters/ai/optimize',
    aiResultKey: 'suggested_parameters',
    columns: [
      { key: 'material_type', label: 'Material' },
      { key: 'geometry_type', label: 'Geometry' },
      { key: 'layer_height', label: 'Layer (mm)' },
      { key: 'nozzle_temp', label: 'Nozzle \u00B0C' },
      { key: 'bed_temp', label: 'Bed \u00B0C' },
      { key: 'print_speed', label: 'Speed mm/s' },
      { key: 'infill_density', label: 'Infill %' },
    ],
    fields: [
      { key: 'material_type', label: 'Material Type', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon', 'PLA+', 'ASA', 'Carbon Fiber PLA', 'Wood PLA'], required: true },
      { key: 'geometry_type', label: 'Geometry Type', type: 'select', options: ['Cube', 'Cylinder', 'Sphere', 'Flat Panel', 'Complex Organic', 'Gear Mechanism', 'Enclosure Box', 'Threaded Part', 'Miniature Figure', 'Outdoor Mount'], required: true },
      { key: 'layer_height', label: 'Layer Height (mm)', type: 'number', step: '0.01' },
      { key: 'nozzle_temp', label: 'Nozzle Temp (\u00B0C)', type: 'number' },
      { key: 'bed_temp', label: 'Bed Temp (\u00B0C)', type: 'number' },
      { key: 'print_speed', label: 'Print Speed (mm/s)', type: 'number' },
      { key: 'infill_density', label: 'Infill Density (%)', type: 'number' },
      { key: 'support_enabled', label: 'Support Enabled', type: 'checkbox' },
    ],
    aiFields: [
      { key: 'material_type', label: 'Material Type', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon', 'PLA+', 'ASA', 'Carbon Fiber PLA', 'Wood PLA'], required: true },
      { key: 'geometry_type', label: 'Geometry Type', type: 'select', options: ['Cube', 'Cylinder', 'Sphere', 'Flat Panel', 'Complex Organic', 'Gear Mechanism', 'Enclosure Box', 'Threaded Part'], required: true },
      { key: 'desired_quality', label: 'Desired Quality', type: 'select', options: ['Draft', 'Standard', 'High', 'Ultra'] },
      { key: 'notes', label: 'Additional Notes', type: 'textarea' },
    ],
  },
  {
    key: 'failure-predictions',
    name: 'Failure Prediction',
    shortName: 'Failure Prediction',
    description: 'AI predicts potential print failures before they happen. Analyze risk levels and get prevention recommendations.',
    icon: '\u26A0\uFE0F',
    isAI: true,
    color: '#ef4444',
    apiPath: '/failure-predictions',
    aiEndpoint: '/failure-predictions/ai/predict',
    aiResultKey: 'prediction',
    columns: [
      { key: 'print_name', label: 'Print Name' },
      { key: 'material_type', label: 'Material' },
      { key: 'geometry_complexity', label: 'Complexity' },
      { key: 'risk_level', label: 'Risk Level', type: 'risk' },
      { key: 'failure_type', label: 'Failure Type' },
    ],
    fields: [
      { key: 'print_name', label: 'Print Name', type: 'text', required: true },
      { key: 'material_type', label: 'Material Type', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon', 'PLA+', 'ASA', 'Carbon Fiber PLA'], required: true },
      { key: 'layer_height', label: 'Layer Height (mm)', type: 'number', step: '0.01' },
      { key: 'nozzle_temp', label: 'Nozzle Temp (\u00B0C)', type: 'number' },
      { key: 'bed_temp', label: 'Bed Temp (\u00B0C)', type: 'number' },
      { key: 'print_speed', label: 'Print Speed (mm/s)', type: 'number' },
      { key: 'geometry_complexity', label: 'Complexity', type: 'select', options: ['Low', 'Medium', 'High'] },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { key: 'failure_type', label: 'Failure Type', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    aiFields: [
      { key: 'material_type', label: 'Material Type', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon', 'PLA+', 'ASA'], required: true },
      { key: 'layer_height', label: 'Layer Height (mm)', type: 'number', step: '0.01', required: true },
      { key: 'nozzle_temp', label: 'Nozzle Temp (\u00B0C)', type: 'number', required: true },
      { key: 'bed_temp', label: 'Bed Temp (\u00B0C)', type: 'number', required: true },
      { key: 'print_speed', label: 'Print Speed (mm/s)', type: 'number', required: true },
      { key: 'geometry_complexity', label: 'Complexity', type: 'select', options: ['Low', 'Medium', 'High'] },
      { key: 'notes', label: 'Additional Notes', type: 'textarea' },
    ],
  },
  {
    key: 'material-selections',
    name: 'Material Selection Advisor',
    shortName: 'Material Advisor',
    description: 'AI recommends the best materials based on your project requirements including strength, flexibility, heat and chemical resistance.',
    icon: '\uD83E\uDDEA',
    isAI: true,
    color: '#10b981',
    apiPath: '/material-selections',
    aiEndpoint: '/material-selections/ai/recommend',
    aiResultKey: 'recommendation',
    columns: [
      { key: 'project_name', label: 'Project' },
      { key: 'application', label: 'Application' },
      { key: 'recommended_material', label: 'Material' },
      { key: 'budget_level', label: 'Budget' },
      { key: 'strength_required', label: 'Strength' },
    ],
    fields: [
      { key: 'project_name', label: 'Project Name', type: 'text', required: true },
      { key: 'application', label: 'Application', type: 'text' },
      { key: 'strength_required', label: 'Strength Required (1-10)', type: 'number' },
      { key: 'flexibility_required', label: 'Flexibility Required (1-10)', type: 'number' },
      { key: 'heat_resistance', label: 'Heat Resistance', type: 'select', options: ['Low', 'Medium', 'High'] },
      { key: 'chemical_resistance', label: 'Chemical Resistance', type: 'select', options: ['Low', 'Medium', 'High'] },
      { key: 'recommended_material', label: 'Recommended Material', type: 'text' },
      { key: 'budget_level', label: 'Budget Level', type: 'select', options: ['Low', 'Medium', 'High'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    aiFields: [
      { key: 'application', label: 'Application/Use Case', type: 'text', required: true },
      { key: 'strength_required', label: 'Strength Required (1-10)', type: 'number', required: true },
      { key: 'flexibility_required', label: 'Flexibility Required (1-10)', type: 'number', required: true },
      { key: 'heat_resistance', label: 'Heat Resistance', type: 'select', options: ['Low', 'Medium', 'High'] },
      { key: 'chemical_resistance', label: 'Chemical Resistance', type: 'select', options: ['Low', 'Medium', 'High'] },
      { key: 'budget_level', label: 'Budget Level', type: 'select', options: ['Low', 'Medium', 'High'] },
      { key: 'notes', label: 'Additional Notes', type: 'textarea' },
    ],
  },
  {
    key: 'build-time-estimates',
    name: 'Build Time Estimation',
    shortName: 'Time Estimation',
    description: 'AI estimates build time with detailed breakdowns by phase. Includes heating, printing, cooling times and cost estimates.',
    icon: '\u23F1\uFE0F',
    isAI: true,
    color: '#f59e0b',
    apiPath: '/build-time-estimates',
    aiEndpoint: '/build-time-estimates/ai/estimate',
    aiResultKey: 'estimate',
    columns: [
      { key: 'model_name', label: 'Model' },
      { key: 'material_type', label: 'Material' },
      { key: 'estimated_hours', label: 'Est. Hours' },
      { key: 'complexity', label: 'Complexity' },
      { key: 'print_speed', label: 'Speed mm/s' },
    ],
    fields: [
      { key: 'model_name', label: 'Model Name', type: 'text', required: true },
      { key: 'dimensions_x', label: 'Width X (mm)', type: 'number' },
      { key: 'dimensions_y', label: 'Depth Y (mm)', type: 'number' },
      { key: 'dimensions_z', label: 'Height Z (mm)', type: 'number' },
      { key: 'layer_height', label: 'Layer Height (mm)', type: 'number', step: '0.01' },
      { key: 'infill_density', label: 'Infill %', type: 'number' },
      { key: 'print_speed', label: 'Speed (mm/s)', type: 'number' },
      { key: 'material_type', label: 'Material', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon', 'Carbon Fiber PLA'] },
      { key: 'estimated_hours', label: 'Estimated Hours', type: 'number', step: '0.1' },
      { key: 'complexity', label: 'Complexity', type: 'select', options: ['Low', 'Medium', 'High'] },
    ],
    aiFields: [
      { key: 'model_name', label: 'Model Name', type: 'text', required: true },
      { key: 'dimensions_x', label: 'Width X (mm)', type: 'number', required: true },
      { key: 'dimensions_y', label: 'Depth Y (mm)', type: 'number', required: true },
      { key: 'dimensions_z', label: 'Height Z (mm)', type: 'number', required: true },
      { key: 'layer_height', label: 'Layer Height (mm)', type: 'number', step: '0.01' },
      { key: 'infill_density', label: 'Infill %', type: 'number' },
      { key: 'print_speed', label: 'Speed (mm/s)', type: 'number' },
      { key: 'material_type', label: 'Material', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon'] },
      { key: 'complexity', label: 'Complexity', type: 'select', options: ['Low', 'Medium', 'High'] },
    ],
  },
  {
    key: 'quality-scores',
    name: 'Quality Scoring',
    shortName: 'Quality Scoring',
    description: 'AI analyzes print quality metrics and provides comprehensive assessments with improvement recommendations.',
    icon: '\u2B50',
    isAI: true,
    color: '#06b6d4',
    apiPath: '/quality-scores',
    aiEndpoint: '/quality-scores/ai/analyze',
    aiResultKey: 'analysis',
    columns: [
      { key: 'print_name', label: 'Print Name' },
      { key: 'material_type', label: 'Material' },
      { key: 'overall_score', label: 'Score' },
      { key: 'surface_quality', label: 'Surface' },
      { key: 'dimensional_accuracy', label: 'Accuracy' },
    ],
    fields: [
      { key: 'print_name', label: 'Print Name', type: 'text', required: true },
      { key: 'surface_quality', label: 'Surface Quality (1-10)', type: 'number' },
      { key: 'dimensional_accuracy', label: 'Dimensional Accuracy (1-10)', type: 'number' },
      { key: 'layer_adhesion', label: 'Layer Adhesion (1-10)', type: 'number' },
      { key: 'detail_resolution', label: 'Detail Resolution (1-10)', type: 'number' },
      { key: 'warping_level', label: 'Warping Level (1-10, 10=none)', type: 'number' },
      { key: 'stringing_level', label: 'Stringing Level (1-10, 10=none)', type: 'number' },
      { key: 'overall_score', label: 'Overall Score', type: 'number', step: '0.1' },
      { key: 'material_type', label: 'Material', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon', 'PLA+', 'ASA', 'Carbon Fiber PLA'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    aiFields: [
      { key: 'print_name', label: 'Print Name', type: 'text', required: true },
      { key: 'surface_quality', label: 'Surface Quality (1-10)', type: 'number', required: true },
      { key: 'dimensional_accuracy', label: 'Dimensional Accuracy (1-10)', type: 'number', required: true },
      { key: 'layer_adhesion', label: 'Layer Adhesion (1-10)', type: 'number', required: true },
      { key: 'detail_resolution', label: 'Detail Resolution (1-10)', type: 'number', required: true },
      { key: 'warping_level', label: 'Warping (1-10, 10=none)', type: 'number', required: true },
      { key: 'stringing_level', label: 'Stringing (1-10, 10=none)', type: 'number', required: true },
      { key: 'material_type', label: 'Material', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon', 'PLA+', 'ASA'] },
      { key: 'notes', label: 'Additional Notes', type: 'textarea' },
    ],
  },
  {
    key: 'print-jobs',
    name: 'Print Jobs Management',
    shortName: 'Print Jobs',
    description: 'Track and manage all print jobs across your printer fleet. Monitor status, priority, and estimated completion times.',
    icon: '\uD83D\uDDA8\uFE0F',
    isAI: false,
    color: '#3b82f6',
    apiPath: '/print-jobs',
    columns: [
      { key: 'job_name', label: 'Job Name' },
      { key: 'printer_name', label: 'Printer' },
      { key: 'material_type', label: 'Material' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'priority', label: 'Priority' },
      { key: 'estimated_time', label: 'Est. Hours' },
    ],
    fields: [
      { key: 'job_name', label: 'Job Name', type: 'text', required: true },
      { key: 'printer_name', label: 'Printer', type: 'text' },
      { key: 'material_type', label: 'Material', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon', 'PLA+', 'ASA', 'Carbon Fiber PLA'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Queued', 'Printing', 'Completed', 'Failed', 'Paused'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Normal', 'High', 'Urgent'] },
      { key: 'estimated_time', label: 'Estimated Time (hours)', type: 'number', step: '0.1' },
      { key: 'file_name', label: 'File Name', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'materials',
    name: 'Material Inventory',
    shortName: 'Materials',
    description: 'Manage your filament and material inventory. Track stock levels, pricing, temperature ranges, and suppliers.',
    icon: '\uD83E\uDDF5',
    isAI: false,
    color: '#10b981',
    apiPath: '/materials',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'type', label: 'Type' },
      { key: 'brand', label: 'Brand' },
      { key: 'color', label: 'Color' },
      { key: 'price', label: 'Price ($)' },
      { key: 'in_stock', label: 'In Stock', type: 'boolean' },
    ],
    fields: [
      { key: 'name', label: 'Material Name', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon', 'PLA+', 'ASA', 'Carbon Fiber PLA', 'Wood PLA'] },
      { key: 'brand', label: 'Brand', type: 'text' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'diameter', label: 'Diameter (mm)', type: 'number', step: '0.01' },
      { key: 'weight_grams', label: 'Weight (g)', type: 'number' },
      { key: 'price', label: 'Price ($)', type: 'number', step: '0.01' },
      { key: 'nozzle_temp_min', label: 'Nozzle Min \u00B0C', type: 'number' },
      { key: 'nozzle_temp_max', label: 'Nozzle Max \u00B0C', type: 'number' },
      { key: 'bed_temp_min', label: 'Bed Min \u00B0C', type: 'number' },
      { key: 'bed_temp_max', label: 'Bed Max \u00B0C', type: 'number' },
      { key: 'in_stock', label: 'In Stock', type: 'checkbox' },
    ],
  },
  {
    key: 'printers',
    name: 'Printer Management',
    shortName: 'Printers',
    description: 'Manage your 3D printer fleet. Track status, build volumes, print hours, and maintenance schedules.',
    icon: '\uD83E\uDD16',
    isAI: false,
    color: '#8b5cf6',
    apiPath: '/printers',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'model', label: 'Model' },
      { key: 'manufacturer', label: 'Manufacturer' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'total_print_hours', label: 'Hours' },
    ],
    fields: [
      { key: 'name', label: 'Printer Name', type: 'text', required: true },
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'manufacturer', label: 'Manufacturer', type: 'text' },
      { key: 'build_volume_x', label: 'Build X (mm)', type: 'number' },
      { key: 'build_volume_y', label: 'Build Y (mm)', type: 'number' },
      { key: 'build_volume_z', label: 'Build Z (mm)', type: 'number' },
      { key: 'nozzle_diameter', label: 'Nozzle (mm)', type: 'number', step: '0.01' },
      { key: 'max_temp', label: 'Max Temp \u00B0C', type: 'number' },
      { key: 'heated_bed', label: 'Heated Bed', type: 'checkbox' },
      { key: 'status', label: 'Status', type: 'select', options: ['Idle', 'Printing', 'Queued', 'Maintenance', 'Offline'] },
      { key: 'total_print_hours', label: 'Total Print Hours', type: 'number', step: '0.1' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'print-profiles',
    name: 'Print Profiles',
    shortName: 'Profiles',
    description: 'Save and manage reusable print profiles for different materials and use cases. Quick-load optimal settings.',
    icon: '\uD83D\uDCC4',
    isAI: false,
    color: '#f59e0b',
    apiPath: '/print-profiles',
    columns: [
      { key: 'profile_name', label: 'Profile' },
      { key: 'material_type', label: 'Material' },
      { key: 'layer_height', label: 'Layer (mm)' },
      { key: 'nozzle_temp', label: 'Nozzle \u00B0C' },
      { key: 'print_speed', label: 'Speed mm/s' },
      { key: 'infill_density', label: 'Infill %' },
    ],
    fields: [
      { key: 'profile_name', label: 'Profile Name', type: 'text', required: true },
      { key: 'material_type', label: 'Material', type: 'select', options: ['PLA', 'ABS', 'PETG', 'TPU', 'Nylon', 'PLA+', 'ASA', 'Carbon Fiber PLA'] },
      { key: 'layer_height', label: 'Layer Height (mm)', type: 'number', step: '0.01' },
      { key: 'nozzle_temp', label: 'Nozzle Temp \u00B0C', type: 'number' },
      { key: 'bed_temp', label: 'Bed Temp \u00B0C', type: 'number' },
      { key: 'print_speed', label: 'Speed (mm/s)', type: 'number' },
      { key: 'infill_density', label: 'Infill %', type: 'number' },
      { key: 'retraction_enabled', label: 'Retraction Enabled', type: 'checkbox' },
      { key: 'retraction_distance', label: 'Retraction Distance (mm)', type: 'number', step: '0.1' },
      { key: 'fan_speed', label: 'Fan Speed (%)', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'maintenance-logs',
    name: 'Maintenance Logs',
    shortName: 'Maintenance',
    description: 'Track printer maintenance activities, costs, and schedules. Keep your fleet in optimal condition.',
    icon: '\uD83D\uDD27',
    isAI: false,
    color: '#ef4444',
    apiPath: '/maintenance-logs',
    columns: [
      { key: 'printer_name', label: 'Printer' },
      { key: 'maintenance_type', label: 'Type' },
      { key: 'performed_by', label: 'Performed By' },
      { key: 'cost', label: 'Cost ($)' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { key: 'printer_name', label: 'Printer', type: 'text', required: true },
      { key: 'maintenance_type', label: 'Type', type: 'select', options: ['Nozzle Replacement', 'Belt Tension', 'Firmware Update', 'Full Service', 'Hotend Clean', 'Bed Replacement', 'Lubrication', 'Calibration', 'Fan Replace', 'Extruder Upgrade', 'Other'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'performed_by', label: 'Performed By', type: 'text' },
      { key: 'cost', label: 'Cost ($)', type: 'number', step: '0.01' },
      { key: 'next_maintenance_date', label: 'Next Maintenance', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['Completed', 'In Progress', 'Scheduled'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
];
